project_id = "umxwoofjvyvnhxbqvciw"

[functions.test-fwc-api]
verify_jwt = false

[functions.get-awards]
verify_jwt = false

[functions.get-classifications]
verify_jwt = false

[functions.get-classification-details]
verify_jwt = false

[functions.calculate-shift-pay]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.send-email-report]
verify_jwt = false

[functions.ai-parse-shifts]
verify_jwt = false

[functions.ai-parse-payslip]
verify_jwt = false
