import { describe,test,expect,mock } from 'bun:test';
const calls:any[]=[];let returned:any[]=[];
mock.module('../src/integrations/supabase/client',{supabase:{functions:{invoke:async(name:string,options:any)=>{calls.push({name,...options});return {data:name==='calculate-shift-pay'?returned.shift():{results:[]},error:null};}}}});
const {calculateAnswers}=await import('../src/features/check/calculate');
const {defaults}=await import('../src/features/check/model');
const result=(amount=25)=>({mode:'unsure',overallMinUnderpayment:amount,overallMaxUnderpayment:amount,likelyClassifications:[{classificationId:'1',possibleUnderpayment:amount,awardPayTotal:200}],reasons:[],potentialAllowances:[]});
describe('guided adapter preserves official engine contract',()=>{
 test('manual overnight shift leaves overtime to engine and uses next-day finish',async()=>{calls.length=0;returned=[result()];const a={...defaults(),awardCode:'MA000009',rate:'24',employmentType:'Casual',shifts:[{date:'2026-10-05',day_of_week:'Monday',start:'22:00',finish:'06:00',break_minutes:30}]};const out=await calculateAnswers(a,()=>{});const body=calls.find(x=>x.name==='calculate-shift-pay').body;expect(body.finishTime).toBe('30:00');expect(body.advancedPayslip).toBeNull();expect(body.actualPaid).toBe(180);expect(out.shiftDetails.hours_worked[0].finish).toBe('06:00');});
 test('period gross is divided across shifts, never repeated per shift',async()=>{calls.length=0;returned=[result(10),result(20)];const a={...defaults(),awardCode:'MA000009',gross:'360',shifts:[{date:'2026-10-05',day_of_week:'Monday',start:'09:00',finish:'17:00',break_minutes:30},{date:'2026-10-06',day_of_week:'Tuesday',start:'09:00',finish:'17:00',break_minutes:30}]};const out=await calculateAnswers(a,()=>{});expect(calls.filter(x=>x.name==='calculate-shift-pay').map(x=>x.body.actualPaid)).toEqual([180,180]);expect(out.result.overallMinUnderpayment).toBe(30);});
 test('hours-only mode does not invent a weekend penalty from period start',async()=>{calls.length=0;returned=[result()];await calculateAnswers({...defaults(),awardCode:'MA000009',gross:'912',hours:'38',usePayslipHours:true,weekStart:'2026-10-04'},()=>{});const body=calls.find(x=>x.name==='calculate-shift-pay').body;expect(body.workedWeekend).toBe(false);expect(body.advancedPayslip.hoursAtBase).toBe(38);});
 test('incompatible classification sets cannot produce a fabricated range',async()=>{calls.length=0;returned=[result(),{...result(),likelyClassifications:[{classificationId:'2',possibleUnderpayment:10}]}];await expect(calculateAnswers({...defaults(),awardCode:'MA000009',gross:'360',shifts:[{date:'2026-10-05',day_of_week:'Monday',start:'09:00',finish:'17:00',break_minutes:30},{date:'2026-10-06',day_of_week:'Tuesday',start:'09:00',finish:'17:00',break_minutes:30}]},()=>{})).rejects.toThrow('same levels');});
});
