import { describe, test, expect } from 'bun:test';
import { applyCheckout } from '../supabase/functions/stripe-webhook/payment.ts';
const id='00000000-0000-4000-8000-000000000002';
function fixture(purchase:any,report:any=null){
 const updates:any[]=[];
 const admin={from:(table:string)=>{const q:any={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:table==='subscription_purchases'?purchase:table==='reports'?report:{credits:2}}),update:(data:any)=>{updates.push({table,data});return q},upsert:async(data:any)=>{updates.push({table,data});return {error:null}},then:(ok:any)=>Promise.resolve({error:null}).then(ok)};return q},rpc:async(name:string,args:any)=>{updates.push({name,args});return {error:null}}};
 return {admin,updates};
}
describe('verified checkout routing, no live services',()=>{
  test('$30 pending purchase activates pass and linked report transaction',async()=>{const f=fixture({id,product:'three_month_pass',status:'pending',report_id:'report-1'});await applyCheckout(f.admin,{id:'cs_test',client_reference_id:id,amount_total:3000,currency:'aud',payment_status:'paid',metadata:{product:'backpay_pack'}});expect(f.updates).toEqual([{name:'complete_pass_purchase',args:{p_purchase_id:id,p_session_id:'cs_test',p_email:null,p_product:'three_month_pass'}}]);});
  test('legacy $10 pending yearly purchase preserved',async()=>{const f=fixture({id,product:'yearly_access',status:'pending'});await applyCheckout(f.admin,{id:'cs_legacy',client_reference_id:id,amount_total:1000,currency:'aud',payment_status:'paid'});expect(f.updates[0].args.p_product).toBe('yearly_access');});
  test('$30 report-only reference retains legacy backpay credits',async()=>{const f=fixture(null,{id,user_id:'owner'});await applyCheckout(f.admin,{id:'cs_pack',client_reference_id:id,amount_total:3000,currency:'aud',payment_status:'paid'});expect(f.updates[0].data.payment_status).toBe('paid');expect(f.updates[1].data.credits).toBe(7);});
  for (const amount of [2400,3300,0]) test(`paid AUD pass honours promo/tax amount ${amount}`,async()=>{const f=fixture({id,product:'three_month_pass'});await applyCheckout(f.admin,{id:'cs_promo',client_reference_id:id,amount_total:amount,currency:'aud',payment_status:'paid'});expect(f.updates[0].args.p_product).toBe('three_month_pass');});
  test('purchase product takes precedence over amount and metadata',async()=>{const f=fixture({id,product:'yearly_access'});await applyCheckout(f.admin,{id:'cs_metadata',client_reference_id:id,amount_total:3000,currency:'aud',payment_status:'paid',metadata:{product:'three_month_pass'}});expect(f.updates[0].args.p_product).toBe('yearly_access');});
  test('unpaid, missing payment status and incorrect currency are ignored',async()=>{const f=fixture({id,product:'three_month_pass'});for(const session of [{payment_status:'unpaid',currency:'aud'},{currency:'aud'},{payment_status:'paid',currency:'usd'},{payment_status:'paid'}])await applyCheckout(f.admin,{id:'cs_ignore',client_reference_id:id,amount_total:3000,...session});expect(f.updates).toEqual([]);});
  test('unknown references, products and irrelevant sessions are ignored',async()=>{for(const purchase of [null,{id,product:'unknown'}]){const f=fixture(purchase);await applyCheckout(f.admin,{id:'cs_unknown',client_reference_id:id,amount_total:42,currency:'aud',payment_status:'paid'});await applyCheckout(f.admin,{id:'cs_invalid',client_reference_id:'invalid',amount_total:3000,currency:'aud',payment_status:'paid'});expect(f.updates).toEqual([]);}});
  test('genuine purchase lookup errors propagate for Stripe retry',async()=>{const admin={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({error:new Error('database unavailable')})})})})};await expect(applyCheckout(admin,{id:'cs_db',client_reference_id:id,currency:'aud',payment_status:'paid'})).rejects.toThrow('database unavailable');});
  test('genuine finalization errors propagate for Stripe retry',async()=>{const f=fixture({id,product:'three_month_pass'});f.admin.rpc=async()=>({error:new Error('transaction failed')});await expect(applyCheckout(f.admin,{id:'cs_db',client_reference_id:id,amount_total:3000,currency:'aud',payment_status:'paid'})).rejects.toThrow('transaction failed');});
  test('legacy already-processed report is idempotent',async()=>{const f=fixture(null,{id,user_id:'owner',stripe_session_id:'cs_duplicate'});await applyCheckout(f.admin,{id:'cs_duplicate',client_reference_id:id,amount_total:3000,currency:'aud',payment_status:'paid'});expect(f.updates).toEqual([]);});
});
