import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { result, shiftDetails, advancedPayslip } = await req.json();

    console.log('Generating PDF report for pay check result');

    const isUnsureMode = result.mode === 'unsure';
    const underpayment = isUnsureMode ? result.overallMaxUnderpayment : (result.underpayment || 0);
    const isUnderpaid = underpayment > 0;

    // Generate a simple text-based report
    let reportText = '='.repeat(60) + '\n';
    reportText += '           AWARDPAY - PAY CHECK REPORT\n';
    reportText += '='.repeat(60) + '\n\n';
    
    const dateStr = new Date().toLocaleDateString('en-AU', { 
      day: 'numeric', 
      month: 'long', 
      year: 'numeric' 
    });
    reportText += `Generated on: ${dateStr}\n\n`;

    reportText += '-'.repeat(60) + '\n';
    reportText += 'RESULT\n';
    reportText += '-'.repeat(60) + '\n';
    
    if (isUnderpaid) {
      reportText += `⚠️  POTENTIAL UNDERPAYMENT DETECTED\n\n`;
      reportText += `   Amount: $${underpayment.toFixed(2)}\n\n`;
      reportText += `   ${isUnsureMode ? 'Based on likely classifications for your work area' : 'For this pay period'}\n`;
    } else {
      reportText += `✓  PAY APPEARS CORRECT\n\n`;
      reportText += `   Your pay looks roughly correct for this period\n`;
    }
    reportText += '\n';

    // Shift Details
    reportText += '-'.repeat(60) + '\n';
    reportText += 'SHIFT DETAILS\n';
    reportText += '-'.repeat(60) + '\n';
    
    if (shiftDetails.hoursWorked) {
      reportText += `Hours Worked:              ${shiftDetails.hoursWorked}\n`;
    }
    if (shiftDetails.hourlyRate) {
      reportText += `Hourly Rate:               $${shiftDetails.hourlyRate}\n`;
    }
    if (shiftDetails.amountPaid) {
      reportText += `Amount Paid:               $${shiftDetails.amountPaid}\n`;
    }
    reportText += '\n';

    // Calculated Entitlements
    if (result.shouldBePaidBreakdown) {
      reportText += '-'.repeat(60) + '\n';
      reportText += 'CALCULATED ENTITLEMENTS\n';
      reportText += '-'.repeat(60) + '\n';

      const breakdown = result.shouldBePaidBreakdown;

      if (breakdown.ordinary) {
        reportText += `Ordinary Hours:            $${breakdown.ordinary.toFixed(2)}\n`;
      }
      if (breakdown.overtime) {
        reportText += `Overtime:                  $${breakdown.overtime.toFixed(2)}\n`;
      }
      if (breakdown.saturday) {
        reportText += `Saturday:                  $${breakdown.saturday.toFixed(2)}\n`;
      }
      if (breakdown.sunday) {
        reportText += `Sunday:                    $${breakdown.sunday.toFixed(2)}\n`;
      }
      if (breakdown.publicHoliday) {
        reportText += `Public Holiday:            $${breakdown.publicHoliday.toFixed(2)}\n`;
      }
      if (breakdown.allowances) {
        reportText += `Allowances:                $${breakdown.allowances.toFixed(2)}\n`;
      }

      reportText += '\n';
      reportText += `TOTAL SHOULD BE PAID:      $${result.shouldBePaid ? result.shouldBePaid.toFixed(2) : '0.00'}\n`;
      reportText += '\n';
    }

    // Disclaimer
    reportText += '='.repeat(60) + '\n';
    reportText += 'DISCLAIMER\n';
    reportText += '='.repeat(60) + '\n';
    reportText += 'This report is for informational purposes only and does not\n';
    reportText += 'constitute legal or financial advice. For official pay disputes\n';
    reportText += 'or employment concerns, please consult with a qualified\n';
    reportText += 'professional or contact the Fair Work Ombudsman.\n\n';
    reportText += 'Report generated by AwardPay - www.awardpay.com.au\n';
    reportText += '='.repeat(60) + '\n';

    // Convert text to base64 (simulating a simple text "PDF")
    const encoder = new TextEncoder();
    const data = encoder.encode(reportText);
    const base64 = btoa(String.fromCharCode(...data));

    return new Response(
      JSON.stringify({ 
        pdf: base64,
        contentType: 'text/plain'
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error) {
    console.error('Error in generate-pdf-report:', error);
    return new Response(
      JSON.stringify({ error: (error as Error).message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
